CI: remove Coveralls
It seems broken: https://github.com/sinatra/mustermann/actions/runs/10470855923/job/28996871106#step:7:21

    [Coveralls] Submitting with config:
    {
      "environment": {
        "pwd": "/home/runner/work/mustermann/mustermann",
        "rails_root": null,
        "simplecov_root": "/home/runner/work/mustermann/mustermann",
        "gem_version": "0.7.2"
      },
      "git": {
        "head": {
          "id": "c1244734fb0c04cec7e1f5e9db9ee7bc791d71f2",
          "author_name": "Hiroshi SHIBATA",
          "author_email": "hsbt@ruby-lang.org",
          "committer_name": "GitHub",
          "committer_email": "noreply@github.com",
          "message": "Merge 7b954d5cee2c4fa4eb6d989a4756ec5b73b23170 into 4f4260496ca23688ecbe8a1ab104d466661a5525"
        },
        "branch": "(HEAD detached at pull/141/merge)",
        "remotes": [
          {
            "name": "origin",
            "url": "https://github.com/sinatra/mustermann"
          }
        ]
      }
    }
    [Coveralls] Submitting to https://coveralls.io/api/v1
    Coveralls encountered an exception:
    RestClient::UnprocessableEntity
    422 Unprocessable Entity
    /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
    /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/2.7.0/net/http.rb:933:in `start'
    /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/coveralls-0.7.2/lib/coveralls/api.rb:24:in `post_json'
    /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/coveralls-0.7.2/lib/coveralls/simplecov.rb:72:in `format'
    /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/simplecov-0.17.1/lib/simplecov/formatter/multi_formatter.rb:10:in `block in format'
    /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/simplecov-0.17.1/lib/simplecov/formatter/multi_formatter.rb:8:in `map'
    /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/simplecov-0.17.1/lib/simplecov/formatter/multi_formatter.rb:8:in `format'
    /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/simplecov-0.17.1/lib/simplecov/result.rb:48:in `format!'
    /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/simplecov-0.17.1/lib/simplecov/configuration.rb:182:in `block in at_exit'
    /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/simplecov-0.17.1/lib/simplecov.rb:201:in `run_exit_tasks!'
    /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/simplecov-0.17.1/lib/simplecov/defaults.rb:29:in `block in <top (required)>'
    {"message":"Couldn't find a repository matching this job.","error":true}

and also https://github.com/sinatra/mustermann/actions/runs/10470855923/job/28996871965#step:7:20

    Coveralls encountered an exception:
    NoMethodError
    undefined method `exists?' for File:Class
    /Users/dentarg/.arm64_rubies/3.2.5/lib/ruby/gems/3.2.0/gems/coveralls-0.7.2/lib/coveralls/configuration.rb:72:in `yaml_config'
    /Users/dentarg/.arm64_rubies/3.2.5/lib/ruby/gems/3.2.0/gems/coveralls-0.7.2/lib/coveralls/configuration.rb:11:in `configuration'
    /Users/dentarg/.arm64_rubies/3.2.5/lib/ruby/gems/3.2.0/gems/coveralls-0.7.2/lib/coveralls/api.rb:65:in `apified_hash'
    /Users/dentarg/.arm64_rubies/3.2.5/lib/ruby/gems/3.2.0/gems/coveralls-0.7.2/lib/coveralls/api.rb:22:in `post_json'
    /Users/dentarg/.arm64_rubies/3.2.5/lib/ruby/gems/3.2.0/gems/coveralls-0.7.2/lib/coveralls/simplecov.rb:72:in `format'
    /Users/dentarg/.arm64_rubies/3.2.5/lib/ruby/gems/3.2.0/gems/simplecov-0.17.1/lib/simplecov/formatter/multi_formatter.rb:10:in `block in format'
    /Users/dentarg/.arm64_rubies/3.2.5/lib/ruby/gems/3.2.0/gems/simplecov-0.17.1/lib/simplecov/formatter/multi_formatter.rb:8:in `map'
    /Users/dentarg/.arm64_rubies/3.2.5/lib/ruby/gems/3.2.0/gems/simplecov-0.17.1/lib/simplecov/formatter/multi_formatter.rb:8:in `format'
    /Users/dentarg/.arm64_rubies/3.2.5/lib/ruby/gems/3.2.0/gems/simplecov-0.17.1/lib/simplecov/result.rb:48:in `format!'
    /Users/dentarg/.arm64_rubies/3.2.5/lib/ruby/gems/3.2.0/gems/simplecov-0.17.1/lib/simplecov/configuration.rb:182:in `block in at_exit'
    /Users/dentarg/.arm64_rubies/3.2.5/lib/ruby/gems/3.2.0/gems/simplecov-0.17.1/lib/simplecov.rb:201:in `run_exit_tasks!'
    /Users/dentarg/.arm64_rubies/3.2.5/lib/ruby/gems/3.2.0/gems/simplecov-0.17.1/lib/simplecov/defaults.rb:29:in `block in <top (required)>'